### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by NguyenCongBi** [dumrauf/b2c2_client#1]
I changed API_TOKEN and run  bug it throw 403 error.please help me fix

**Comment by dumrauf** [comment]
Hi, thanks for opening the issue.

Without much more information, my best guess is that your API_TOKEN might have insufficient privileges. The HTTP 403 status code indicates that you don't have the necessary permissions to carry out the request. Feel free to have a look at https://en.wikipedia.org/wiki/HTTP_403 and see if a new token resolves the problem.

All the best!

**Comment by NguyenCongBi** [comment]
This is token.please help me
![Capture](https://user-images.githubusercontent.com/12244219/64249553-23f9b480-cf3e-11e9-9d98-c2112badb7d9.PNG)
